DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    userId IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);


DROP TABLE IF EXISTS UserDevice;

CREATE TABLE UserDevice (
    userId INTEGER NOT NULL,
    deviceHash VARCHAR NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(userId),
    CONSTRAINT USERDEVICE_UK (userId,deviceHash)
);


DROP TABLE IF EXISTS UserToken;

CREATE TABLE UserToken (
    userId INTEGER NOT NULL PRIMARY KEY,
    token VARCHAR NOT NULL
    FOREIGN KEY (userId) REFERENCES Users(userId),
    UNIQUE KEY TOKEN_UK (token)
);


DROP TABLE IF EXISTS UserBankCard;

CREATE TABLE UserBankCard (
    userId INTEGER NOT NULL PRIMARY KEY,
    cardId VARCHAR NOT NULL,
    cardnumber INTEGER NOT NULL,
    cvc INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    amount INTEGER DEFAULT 0,
    currency VARCHAR NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(userId),
);









