-----USERDATEILS-------
DROP TABLE IF EXISTS Users;

CREATE TABLE Users
(
    USER_ID INTEGER NOT NULL,
    NAME    VARCHAR(100) NOT NULL,
    EMAIL   VARCHAR(100) NOT NULL,
    CONSTRAINT users_PK PRIMARY KEY (USER_ID)
);

--
DROP TABLE IF EXISTS UserDevice;

CREATE TABLE UserDevice
(
    USER_ID     INTEGER NOT NULL,
    DEVICE_HASH VARCHAR(255) NOT NULL,
    CONSTRAINT userdevice_PK PRIMARY KEY (DEVICE_HASH),
    CONSTRAINT userdevice_user_FK FOREIGN KEY (USER_ID) REFERENCES Users (USER_ID)
);

--
DROP TABLE IF EXISTS UserToken;

CREATE TABLE UserToken
(
    USER_ID INTEGER NOT NULL,
    TOKEN   VARCHAR(255) NOT NULL,
    CONSTRAINT usertoken_PK PRIMARY KEY (TOKEN),
    CONSTRAINT usertoken_user_FK FOREIGN KEY (USER_ID) REFERENCES Users (USER_ID)
);


DROP TABLE IF EXISTS UserBankCard;

CREATE TABLE UserBankCard
(
    USER_ID     INTEGER NOT NULL,
    CARD_ID     VARCHAR(100) NOT NULL,
    CARD_NUMBER VARCHAR(100) NOT NULL,
    CVC         INTEGER NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    AMOUNT      INTEGER DEFAULT 0,
    CURRENCY    VARCHAR(100) NOT NULL,
    CONSTRAINT userbankcard_PK PRIMARY KEY (CARD_ID),
    CONSTRAINT userbankcard_user_FK FOREIGN KEY (USER_ID) REFERENCES Users (USER_ID),
    CONSTRAINT userbankcard_UI UNIQUE (CARD_NUMBER)

);

------EVENTDETAILS-------

DROP TABLE IF EXISTS Event;

CREATE TABLE Event
(
    EVENT_ID   INTEGER   NOT NULL,
    TITLE      VARCHAR(100)   NOT NULL,
    LOCATION   VARCHAR(100)   NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME   TIMESTAMP NOT NULL,
    CONSTRAINT event_PK PRIMARY KEY (EVENT_ID)

);

DROP TABLE IF EXISTS Seat;

CREATE TABLE Seat
(
    ID       VARCHAR(100) NOT NULL,
    EVENT_ID INTEGER NOT NULL,
    PRICE    INTEGER NOT NULL,
    CURRENCY VARCHAR(100) NOT NULL,
    RESERVED BOOLEAN DEFAULT FALSE,
    CONSTRAINT seat_event_UI PRIMARY KEY (ID,EVENT_ID),
    CONSTRAINT seat_event_FK FOREIGN KEY (EVENT_ID) REFERENCES Event (EVENT_ID)
);
