DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    USER_ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL
);


DROP TABLE IF EXISTS UserDevice;

CREATE TABLE UserDevice (
    USER_ID INTEGER NOT NULL,
    DEVICE_HASH VARCHAR NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(USER_ID),
    CONSTRAINT USERDEVICE_UK (USER_ID,DEVICE_HASH)
);


DROP TABLE IF EXISTS UserToken;

CREATE TABLE UserToken (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    TOKEN VARCHAR NOT NULL
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    UNIQUE KEY TOKEN_UK (TOKEN)
);


DROP TABLE IF EXISTS UserBankCard;

CREATE TABLE UserBankCard (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    CARD_ID VARCHAR NOT NULL,
    CARD_NUMBER INTEGER NOT NULL,
    CVC INTEGER NOT NULL,
    NAME VARCHAR NOT NULL,
    AMOUNT INTEGER DEFAULT 0,
    CURRENCY VARCHAR NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
);









